version: '3.8'

services:
  proxy:    
    build:
      context: .
      dockerfile: Dockerfile
      target: web_proxy
    container_name: proxy
    ports:
      - 8082:80
      - 443:443
    # depends_on:
    #   - web
      

  web:      
    build:
      context: .
      dockerfile: Dockerfile      
      target: web_app
    image: web_app
    container_name: web
  #   # ports:
  #     # - 9000:9000
    

# volumes:
  # web_public:  